"""empty message

Revision ID: 67a2b6c29a19
Revises: 
Create Date: 2018-02-12 19:37:06.982928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a2b6c29a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Category',
    sa.Column('cat_id', sa.String(length=100), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=True),
    sa.Column('cat_desc', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('Recipe',
    sa.Column('recipe_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(length=120), nullable=True),
    sa.Column('steps', sa.String(length=120), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['Category.cat_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_table('Review',
    sa.Column('review_id', sa.String(length=120), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=True),
    sa.Column('recipe_id', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('UpVote',
    sa.Column('vote_id', sa.String(length=120), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UpVote')
    op.drop_table('Review')
    op.drop_table('Recipe')
    op.drop_table('Category')
    op.drop_table('User')
    # ### end Alembic commands ###
