"""empty message

Revision ID: 06e1c5c0122b
Revises: 503705fd248b
Create Date: 2017-10-05 15:51:01.953120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e1c5c0122b'
down_revision = '503705fd248b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Recipe_ingredients_key', 'Recipe', type_='unique')
    op.drop_constraint('Recipe_steps_key', 'Recipe', type_='unique')
    op.drop_constraint('Recipe_title_key', 'Recipe', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Recipe_title_key', 'Recipe', ['title'])
    op.create_unique_constraint('Recipe_steps_key', 'Recipe', ['steps'])
    op.create_unique_constraint('Recipe_ingredients_key', 'Recipe', ['ingredients'])
    # ### end Alembic commands ###
