"""empty message

Revision ID: 17b59956db0c
Revises: 06e1c5c0122b
Create Date: 2017-10-05 20:58:37.796255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b59956db0c'
down_revision = '06e1c5c0122b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_email_key', 'User', type_='unique')
    op.drop_constraint('User_name_key', 'User', type_='unique')
    op.drop_constraint('User_password_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_password_key', 'User', ['password'])
    op.create_unique_constraint('User_name_key', 'User', ['name'])
    op.create_unique_constraint('User_email_key', 'User', ['email'])
    # ### end Alembic commands ###
