"""empty message

Revision ID: 19f16524cd21
Revises: 
Create Date: 2017-11-24 09:36:46.536747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f16524cd21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Category',
    sa.Column('cat_id', sa.String(length=100), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=True),
    sa.Column('cat_desc', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.username'], ),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('cat_name')
    )
    op.create_table('Recipe',
    sa.Column('recipe_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(length=120), nullable=True),
    sa.Column('steps', sa.String(length=120), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['Category.cat_name'], ),
    sa.ForeignKeyConstraint(['created_by'], ['User.username'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recipe')
    op.drop_table('Category')
    op.drop_table('User')
    # ### end Alembic commands ###
