"""empty message

Revision ID: 503705fd248b
Revises: 
Create Date: 2017-10-05 15:29:09.246278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503705fd248b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('modified_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'modified_date')
    # ### end Alembic commands ###
