"""empty message

Revision ID: 5c0700601db1
Revises: 
Create Date: 2017-10-12 23:30:02.036651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0700601db1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Category',
    sa.Column('cat_id', sa.String(length=100), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=True),
    sa.Column('cat_desc', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('Recipe',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('ingredients', sa.String(length=120), nullable=True),
    sa.Column('steps', sa.String(length=120), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['Category.cat_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recipe')
    op.drop_table('Category')
    op.drop_table('User')
    # ### end Alembic commands ###
