"""empty message

Revision ID: 6ccb56ae0815
Revises: 5c0700601db1
Create Date: 2017-10-12 23:31:08.293603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccb56ae0815'
down_revision = '5c0700601db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Category', ['cat_name'])
    op.drop_constraint('Recipe_category_fkey', 'Recipe', type_='foreignkey')
    op.create_foreign_key(None, 'Recipe', 'Category', ['category'], ['cat_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe', type_='foreignkey')
    op.create_foreign_key('Recipe_category_fkey', 'Recipe', 'Category', ['category'], ['cat_id'])
    op.drop_constraint(None, 'Category', type_='unique')
    # ### end Alembic commands ###
