"""empty message

Revision ID: 6d6b3521becd
Revises: e18b4fbc0896
Create Date: 2017-12-01 20:27:42.286208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6b3521becd'
down_revision = 'e18b4fbc0896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'upvotes')
    # ### end Alembic commands ###
