"""empty message

Revision ID: 743771a30631
Revises: 6d6b3521becd
Create Date: 2017-12-01 20:32:06.934975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743771a30631'
down_revision = '6d6b3521becd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UpVote',
    sa.Column('vote_id', sa.String(length=120), nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['User.username'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.recipe_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UpVote')
    # ### end Alembic commands ###
