"""empty message

Revision ID: c18f82e190b6
Revises: 743771a30631
Create Date: 2017-12-10 12:21:22.592880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18f82e190b6'
down_revision = '743771a30631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Recipe', sa.Column('reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Recipe', 'reviews')
    # ### end Alembic commands ###
